
- name: Install Redis Repo 
  yum: 
    name: https://rpms.remirepo.net/enterprise/remi-release-7.9-3.el8.rpm
    state: present

- name : Install Redis 
  yum: 
    name: redis
    enablerepo: remi 
    state: present

- name: Update Redis Listen Address
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis Service
  systemd: 
    name: redis
    enabled: yes
    state: started 