- name: Copy Logstash Config
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Stop Logstash 
  systemd:
    name: logstash 
    state: stopped

- name: Waits for port 5044 to be stopped
  ansible.builtin.wait_for:
    port: 5044
    delay: 10
    state: stopped 
