- name: Demo on Variables
  hosts: all
  vars: 
    URL1: play.google.com
    ##play level
  vars_files: 
    - vars.yml
  tasks:
    - name: Print a Variable
      debug: 
        msg: URL={{URL1}}
    - name: Print a Variable from file
      debug:
        msg: URL={{URL2}}