- name:  Demo on Filters
  hosts: localhost
  vars: 
    URL: https://get.jenkins.io/war-stable/2.452.2/jenkins.war
  tasks: 
    - name: Print file(last value) of a url
      debug: 
        msg: FILE = {{URL | split("/") | last}}