
- name: Copy MySQL Repo
  copy: 
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs Package
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL Server 
  yum: 
    name: mysql-community-server
    state: present

- name: Start MySQL Service
  systemd: 
    name: mysqld
    state: started 
    enabled: yes 

- name: Check the Password Reset Status
  shell: echo 'show databases' | mysql -uroot -pRoboShop@1
  register: out 
  ignore_errors: true 
 

- name: Grab default password
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: default_pass
  when: out.rc != 0

- name: Reset SQL file
  copy: 
    src: reset.sql
    dest: /tmp/reset.sql
  when: out.rc != 0

- name: Reset MySQL Password 
  shell: mysql --connect-expired-password -u root -p"{{default_pass.stdout}}" </tmp/reset.sql
  when: out.rc != 0


- name: Check Password Validate plugin
  shell: echo 'show plugins;' | mysql -u root -p"RoboShop@1" 2>/dev/null | grep -i validate_password
  register: val_out
  ignore_errors: true 

- name: Uninstall Validate plugin
  shell: echo "uninstall plugin validate_password;" >/tmp/pass.sql ; mysql -u root -p"RoboShop@1" </tmp/pass.sql 
  when: val_out.rc == 0 

# - name: Download MySQL Schema
#   ansible.builtin.unarchive: 
#     src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
#     dest: /tmp
#     remote_src: yes

# - name: Load Schema
#   community.mysql.mysql_db:
#     state: import
#     name: all
#     target: /tmp/mysql-main/shipping.sql
#     login_password: RoboShop@1
#     login_user: root  