- name: Import filebeat RPM key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copy Yum Repo file
  copy: 
    src: es.repo
    dest: /etc/yum.repos.d/es.repo

- name: Install filebeat 
  yum: 
    name: filebeat 
    state: installed 

- name: Start filebeat Service 
  systemd: 
    name: filebeat
    state: restarted
    enabled: yes 

