
- name: Download Node Exporter 
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz"
    dest: /opt
    remote_src: yes

- name: Create link of prometheus with standard directory name
  ansible.builtin.file:
    src: node_exporter-1.8.1.linux-amd64      
    dest: /opt/node_exporter
    state: link