
- name: Install Python 
  yum: 
    name: 
      - python36 
      - gcc
      - python3-devel
    state: present

- name: Download
  include_tasks: download.yml

  
- name: Install Python Dependencies
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Systemd 
  include_tasks: systemd.yml


