groups:
  - name: HardwareResources
    rules:
      - alert: HighCPU
        expr: cpu_usage_in_percentage > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: HighCPU on {%raw%}{{ $labels.tagName }}{%endraw%}

  - name: HardwareResources
    rules:
      - alert: CartServiceDown
        expr: node_systemd_unit_state{name="cart.service",tagName="cart",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{%raw%}Service {{ $labels.tagName }} Down on {{ $labels.tagName }}{%endraw%}"





