route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: "email"
    email_configs:
      - to: keerthinallagundla@gmail.com      # you@example.com
        from: keerthinallagundla@gmail.com # alertmanager@example.com
        smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: AKIAU6GD3EITZV5LDJAL
        auth_password: BJJ/NPhjCQiia/cy/dm7P7ffVHybOuOksnaCK7YUzvvP
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

